name: Test
# Controls when the action will run.
on:
  # Triggers
  pull_request:
    branches:
      - master
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    name: Node ${{matrix.node}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: git fetch origin master
      - run: npm ci -D
      - run: npm run ng affected:test -- --base=origin/master
